export const addPolicyForm = [
  {
    level: 1,
    type_input: 'input',
    keyboardType: 'text',
    label: 'label.names',
    name: 'name',
    autoCapitalize: true,
  },
  {
    level: 2,
    type_input: 'input',
    keyboardType: 'text',
    name: 'lastName',
    label: 'label.lastname',
    autoCapitalize: true,
  },
  {
    level: 3,
    type_input: 'input',
    keyboardType: 'email',
    label: 'label.email',
    name: 'email',
  },
  {
    level: 4,
    type_input: 'input',
    keyboardType: 'numeric',
    label: 'label.mobile_phone',
    name: 'phone',
    maxLength: 10,
  },
  {
    level: 5,
    type_input: 'radio-button',
    data: [
      { id: 1, text: 'natural_person', value: 1 },
      { id: 2, text: 'legal_entity', value: 2 },
    ],
    name: 'rfc',
  },
  {
    level: 6,
    type_input: 'upload',
    name: 'img',
  },
];

export const carForm = [
  {
    level: 1,
    type_input: 'input',
    keyboardType: 'text',
    label: 'label.alias',
    placeholder: 'placeholders.e_g_amys_car',
    name: 'alias',
  },
  {
    level: 2,
    keyboardType: 'email',
    label: 'label.email',
    name: 'email',
    type_input: 'input',
  },
  {
    level: 3,
    keyboardType: 'numeric',
    returnKeyType: 'done',
    label: 'label.mobile_phone',
    name: 'phone',
    type_input: 'input',
    maxLength: 10,
    variant: 'phone',
  },
  {
    level: 4,
    keyboardType: 'numeric',
    returnKeyType: 'done',
    label: 'label.zip_code',
    name: 'postalCode',
    type_input: 'input',
  },
  {
    level: 5,
    label: 'label.gender',
    type_input: 'radio-button',
    data: [
      { id: 1, text: 'male', value: 1 },
      { id: 2, text: 'female', value: 2 },
    ],
    name: 'gender',
  },
  {
    level: 6,
    variant: 'date',
    label: 'label.birth_date',
    name: 'birthdate',
    type_input: 'input',
  },
];

export const healthForm = [
  {
    level: 1,
    label: 'label.insurance_type',
    placeholder: 'placeholders.select',
    name: 'insuranceType',
    type_input: 'dropdown',
  },
  {
    level: 2,
    type_input: 'input',
    keyboardType: 'text',
    label: 'label.alias',
    placeholder: 'placeholders.e_g_amys_health',
    name: 'alias',
  },
  {
    level: 3,
    type_input: 'separator',
    label: 'text.verify_your_information',
  },
  {
    level: 4,
    label: 'label.gender',
    type_input: 'radio-button',
    data: [
      { id: 1, text: 'male', value: 1 },
      { id: 2, text: 'female', value: 2 },
    ],
    name: 'gender',
  },
  {
    level: 5,
    variant: 'date',
    label: 'label.birth_date',
    name: 'birthdate',
    type_input: 'input',
  },
  {
    level: 6,
    keyboardType: 'email',
    label: 'label.email',
    name: 'email',
    type_input: 'input',
  },
  {
    level: 7,
    keyboardType: 'numeric',
    returnKeyType: 'done',
    label: 'label.mobile_phone',
    name: 'phone',
    type_input: 'input',
    maxLength: 10,
  },
];

export const homeForm = [
  {
    level: 1,
    type_input: 'input',
    keyboardType: 'text',
    label: 'label.alias',
    placeholder: 'placeholders.e_g_apartment_retirement',
    name: 'alias',
  },
  {
    level: 2,
    keyboardType: 'email',
    label: 'label.email',
    name: 'email',
    type_input: 'input',
  },
  {
    level: 3,
    keyboardType: 'numeric',
    returnKeyType: 'done',
    label: 'label.mobile_phone',
    name: 'phone',
    type_input: 'input',
    maxLength: 10,
  },
  {
    level: 4,
    keyboardType: 'numeric',
    returnKeyType: 'done',
    label: 'label.zip_code',
    name: 'postalCode',
    type_input: 'input',
  },
  {
    level: 5,
    keyboardType: 'text',
    label: 'label.state_province',
    name: 'state_providence',
    type_input: 'input',
  },
  {
    level: 6,
    keyboardType: 'text',
    label: 'label.city',
    name: 'city',
    type_input: 'input',
  },
  {
    level: 7,
    keyboardType: 'text',
    label: 'label.adress_line_1',
    name: 'suburb',
    type_input: 'input',
  },
  {
    level: 8,
    keyboardType: 'text',
    label: 'label.adress_line_2',
    name: 'adress_line_2',
    type_input: 'input',
  },
  {
    level: 9,
    label: 'label.housing_status',
    placeholder: 'placeholders.select',
    name: 'housingStatus',
    type_input: 'dropdown',
  },
  {
    level: 10,
    label: 'label.content',
    placeholder: 'placeholders.select',
    name: 'content',
    type_input: 'dropdown',
    button_info: true,
  },
  {
    level: 11,
    label: 'label.liability',
    placeholder: 'placeholders.select',
    name: 'liability',
    type_input: 'dropdown',
  },
  {
    level: 12,
    label: 'label.crystals',
    placeholder: 'placeholders.select',
    name: 'crystals',
    type_input: 'dropdown',
    optionalText: 'optional',
  },
  {
    level: 13,
    label: 'label.jewerly',
    placeholder: 'placeholders.select',
    name: 'jewerly',
    type_input: 'dropdown',
    optionalText: 'optional',
  },
  {
    level: 14,
    label: 'label.electronic_equipment',
    placeholder: 'placeholders.select',
    name: 'electronicEquipment',
    type_input: 'dropdown',
    optionalText: 'optional',
  },
  {
    level: 15,
    label: 'label.robbery',
    placeholder: 'placeholders.select',
    name: 'robbery',
    type_input: 'dropdown',
    optionalText: 'optional',
  },
  {
    level: 16,
    label: 'label.include_debris_removal',
    data: [
      { id: 1, text: 'yes', value: 1 },
      { id: 2, text: 'no', value: 2 },
    ],
    type_input: 'radio-button',
    optionalText: 'optional',
  },
];

export const quoteCarFrom = [
  {
    level: 1,
    label: 'label.year',
    placeholder: 'placeholders.select',
    name: 'year',
    type_input: 'dropdown',
  },
  {
    level: 2,
    label: 'label.brand',
    placeholder: 'placeholders.select',
    name: 'brand',
    type_input: 'dropdown',
  },
  {
    level: 3,
    label: 'label.model',
    placeholder: 'placeholders.select',
    name: 'model',
    type_input: 'dropdown',
  },
  {
    level: 4,
    label: 'label.version',
    placeholder: 'placeholders.select',
    name: 'version',
    type_input: 'dropdown',
  },
  {
    level: 5,
    variant: 'text-area',
    label: 'label.characteristics',
    name: 'characteristics',
    type_input: 'input',
  },
  {
    level: 6,
    label: 'label.what_type_of_coverage',
    placeholder: 'placeholders.select',
    name: 'coverage',
    type_input: 'dropdown',
  },
  {
    level: 7,
    label: 'label.what_payment_method',
    placeholder: 'placeholders.select',
    name: 'payment_method',
    type_input: 'dropdown',
  },
];

export const addBeneficiaryForm = [
  {
    level: 1,
    label: 'label.beneficiary',
    placeholder: 'placeholders.select',
    name: 'beneficiary',
    type_input: 'dropdown',
  },
  {
    level: 2,
    label: 'label.gender',
    type_input: 'radio-button',
    data: [
      { id: 1, text: 'male', value: 1 },
      { id: 2, text: 'female', value: 2 },
    ],
    name: 'gender',
  },
  {
    level: 3,
    variant: 'date',
    label: 'label.birth_date',
    name: 'birthdate',
    type_input: 'input',
  },
];
